<h3>Editar Tipo de Produto</h3>
<br />

<?php
$form = $this->form;

$form->setAttribute('action', $this->url("produto/default", array('controller'=>'tipos', 'action' => 'edit')));

$form->prepare();
   echo $this->form()->openTag($form);
   echo $this->formRow($form->get('id'));
   echo $this->formRow($form->get('nome'));
   echo $this->formRow($form->get('codigo'));
   echo $this->formRow($form->get('submit'));
   echo $this->form()->closeTag();
?>
